### ISSUE TITLE
Improve welcome message

### ISSUE THREAD

**Issue by sidntrivedi** [osdc/bots#21]
## New feature

Discord uses some really cool welcome messages, we would love to have them in our bot too.

## Directions/Approach

Just tweak the function where we send the welcome message and randomly select a string of various hard-coded welcome messages.
## First-time Contributors

**If it is the first time that you contribute to the bot, follow these steps:**

1. You need to have **git & golang** available on your machine. 
    - To install Git - https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
    - To setup golang, follow the doc here - https://golang.org/doc/install
2. Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.`
3. Ping [Botfather](https://t.me/BotFather) on Telegram and make your instance of OSDC-Bot bot by selecting `/newbot` from the options it provides.
4. Copy the `TELEGRAM_TOKEN` provided by Botfather. 
5. Fork this repo.
6. Run `git clone https://github.com/<YOUR_USERNAME>/bots.git && cd bots/telegram-bot`
7. If you have installed golang, run `go build .` 
8. Wait ⏳
9. Run `export TELEGRAM_TOKEN=<botfather_token>`
10. Now, run `./telegram-bot`. The bot would be running at the user handle provided by you.
11. Make changes according to the issue. Test the working of the changes.
12. Commit the changes and then run `git push origin master` and then open a PR! 🎉

**Comment by DelusionalOptimist** [comment]
Hey all, I would like to work on the issue.

**Comment by sidntrivedi** [comment]
Hey @DelusionalOptimist, have you setup the project?

**Comment by DelusionalOptimist** [comment]
Yes @sidntrivedi012, I have setup the project.

**Comment by sidntrivedi** [comment]
Great, here's the welcome function - https://github.com/osdc/bots/blob/master/telegram-bot/main.go#L80-L85

We just need to list down the welcome strings and then then randomly select any one and send it. Makes sense? Do ask if you have any doubts.

**Comment by DelusionalOptimist** [comment]
Thanks for the help @sidntrivedi012.  :relaxed:
