### ISSUE TITLE
Change repo link in /help message

### ISSUE THREAD

**Issue by daemon1024** [osdc/bots#29]
### Changes to be made

https://github.com/osdc/bots/blob/79b0c0137cd396b5eb1bb5e2669dba852b6aa110/telegram-bot/main.go#L67

Updating the above mentioned repository link with https://github.com/osdc/bots

**Hi, If it is the first time that you contribute to the bot, follow these steps:**

Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.` and follow [Contributing to the bot 🔥✨](https://github.com/osdc/bots/blob/master/CONTRIBUTING.md)

**Comment by PrimalPimmy** [comment]
Hey all, I would like to work on this issue.
