### ISSUE TITLE
Pastebin integration

### ISSUE THREAD

**Issue by daemon1024** [osdc/bots#30]
## New feature
Leverage any of the pastebin api's available out there and integrate it with our bot. 

## Why to we need it?
To paste the logs sent by any member for an encountered issue for convenience of other members in the chat who want to help them out.

## Directions/Approach
Using the API as mentioned in http://ix.io/ and https://paste.rs/ ( any one of em or any other better alternative if available )

**Comment by daemon1024** [comment]
@sidntrivedi012 What do you think about this? Can you assign this to me if it seems viable?

**Comment by siddhant-deepsource** [comment]
Sure, you can work on it in a separate branch. Will try to deploy the master today.

**Comment by sidntrivedi** [comment]
@daemon1024 You can work on it in a separate branch as of now. Will deploy the master.
