### ISSUE TITLE
Change timezone used for saving meetups and scheduling reminders

### ISSUE THREAD

**Issue by DelusionalOptimist** [osdc/bots#41]
## Description
Currently the meetup time and reminder schedules are stored in `Local` timezone of the host machine. 
This creates issues when the bot is deployed on some cloud platform because the `Local` time for the host machine may be different.
## Changes to be made
In [`meetup.go`](https://github.com/osdc/bots/blob/master/telegram-bot/meetup.go), replace instances where `Local` time is used, to use Indian time instead.

One such instance:-
https://github.com/osdc/bots/blob/e3920af23da1d8bd3cf825a9152e055c19b57b29/telegram-bot/meetup.go#L98

## First time contributors
**Hi, If it is the first time that you contribute to the bot:**

Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.`, follow [Contributing to the bot 🔥✨](https://github.com/osdc/bots/blob/master/CONTRIBUTING.md) and feel free to ask anything related to this issue ✌️

**Comment by starkah** [comment]
Hello! I would like to work on this issue.

**Comment by daemon1024** [comment]
@starkah Hey 👋. Thanks for showing your interest in this. Feel free to ask any queries while you work on it.
