### ISSUE TITLE
Auto delete " I don't know that command " after a few seconds

### ISSUE THREAD

**Issue by daemon1024** [osdc/bots#42]
## New feature

The bot sends a " I don't know that command " message when it encounters an unknown command. The bot should delete it's message after a few seconds when the user has perceived it. 

**Hi, If it is the first time that you contribute to the bot, follow these steps:**

Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.`, follow [Contributing to the bot 🔥✨](https://github.com/osdc/bots/blob/master/CONTRIBUTING.md) and feel free to ask anything related to this issue ✌️

**Comment by PrimalPimmy** [comment]
I'd like to work on this issue.
