### ISSUE TITLE
Bot crashes when '/nextmeetup' is executed

### ISSUE THREAD

**Issue by osBins** [osdc/bots#46]
![Screenshot from 2020-10-27 00-15-45](https://user-images.githubusercontent.com/70942982/97214979-df884280-17e9-11eb-8668-c764292673b1.png)

Bot **crashes** when the command **'/nextmeetup'** is given. No subsequent commands given to the bot produce a result unless the **bot is restarted.**

Expected to give details of the next meetup if there is a meetup scheduled, and print 'No meetup scheduled' if meetup is not scheduled.

OS: Manjaro, Linux 5.8

**Comment by daemon1024** [comment]
@osBins Thanks for reporting it. Would you like to work on it to fix this?

**Comment by osBins** [comment]
@daemon1024 Yes, I would like to work on this issue.
