### ISSUE TITLE
Add command handlers

### ISSUE THREAD

**Issue by daemon1024** [osdc/bots#61]
We currently use `else.. if` chains for various commands implemented in the bot. It is fine for the very few commands we have but as we scale to add more commands and more features it will cause a lot of unorganized code and make it harder to debug. So we should implement a handler for that.

The discord.js guide has an amazing explanation of how to implement it. 
https://discordjs.guide/command-handling/

**If it is the first time that you contribute to the bot, follow these steps:**

Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.`, follow [Contributing to the bot 🔥✨](https://github.com/osdc/bots/blob/master/discord-bot/README.md) and feel free to ask anything related to this issue ✌️

**Comment by reapedjuggler** [comment]
Hey everyone , I would like to work on this issue :D
